<?php
/**
 * @file
 * Spider Calendar module for Drupal 6.
 *
 * Written by Webdorado team.
 */

/**
 * Implements hook_help().
 */
function spider_calendar_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#spider_calendar":
      $output .= t("Download 'jscolor' library form !url_jscolor and extract it to 'sites/all/libraries/jscolor' directory.<br /><br />
      To show HTML editor in <strong>Administer > Spider Calendar > Calendars > Manage event > HTML</strong> field download 'tinymce' library from !url_html_tiny and extract it to 'sites/all/libraries/tinymce directory'.<br /><br />
      <h4><strong>Step 1: <a target='_blank' href='http://web-dorado.com/drupal-event-calendar-guide-step-2.html'>Creating/Editing Calendars.</a></strong></h4>
      <p>
        <strong>1.1 </strong>From the <strong>Navigation</strong> menu click on <strong>Administer > Site configuration > Spider Calendar</strong>.
      </p>
      <p>
        <strong>1.2 </strong>Click on <strong>New</strong> on the upper left hand of the pop-up window..
      </p>
      <p>
        <strong>1.3 Title.</strong> Add a title for the calendar.
      </p>
      <p>
        <strong>1.4 Published.</strong> Choose whether to publish the calendar or not.
      </p>
      <p>
        <strong>1.5 </strong>Click on the <strong>Save</strong> button to save the created calendar.
      </p>
      <div style='text-align:right;'><a target='_blank' href='http://web-dorado.com/drupal-event-calendar-guide-step-2.html'>More</a></div>
      <h4><strong>Step 2: <a target='_blank' href='http://web-dorado.com/drupal-event-calendar-guide-step-3.html'>Creating/Editing Events.</a></strong></h4>
      <p>
        <strong>2.1 </strong>From the <strong>Navigation</strong> menu click on <strong>Administer > Site configuration > Spider Calendar</strong>.
      </p>
      <p>
        <strong>2.2 </strong>Locate the calendar for which you want to create/edit events and click on the corresponding <strong>Manage Events</strong> link.
      </p>
      <p>
        <strong>2.3 </strong>Click <strong>New</strong> on the upper left hand of the window.
      </p>
      <p>
        <strong>2.4 Title.</strong> Specify a title for the event.
      </p>
      <p>
        <strong>2.5 Date.</strong> Select the event date.
      </p>
      <p>
        <strong>2.6 Time.</strong> Specify the starting and ending times of the event (Optional).
      </p>
      <p>
        <strong>2.7 Note.</strong> Here you can add a description for the event.
      </p>
      <p>
        <strong>2.8 Published.</strong> Choose whether to publish the event or not.
      </p>
      <p>
        <strong>2.9 Repeat Event.</strong> Select a repeat mode for the event.
        <ul>
          <li><strong>Don't repeat this event.</strong></li>
          <li><strong>Repeat daily.</strong> Choose a periodicity for repeating the event (e.g. every 7 days).</li>
          <li><strong>Repeat weekly.</strong> Choose a periodicity for repeating the event (e.g. every 2 weeks) and the day of the week.</li>
          <li><strong>Repeat monthly.</strong> Choose a periodicity for repeating the event (e.g. every 3 months) and the day of the month.</li>
          <li><strong>Repeat yearly.</strong> Choose a periodicity for repeating the event (e.g. every 2 years), the month of the year, and the day of the month.</li>
          <li><strong>Repeat until.</strong> Choose the end date for repeating the event.</li>
        </ul>
      </p>
      <p>
        <strong>2.10 </strong>Click on the <strong>Save</strong> button to save the created event.
      </p>
      <div style='text-align:right;'><a target='_blank' href='http://web-dorado.com/drupal-event-calendar-guide-step-3.html'>More</a></div>
      <h4><strong>Step 3: <a target='_blank' href='http://web-dorado.com/4-creatingediting-calendar-themes/drupal-event-calendar-guide-step-4-1.html'>Creating/Editing Calendar Themes.</a></strong></h4>
      <p>
        <strong>3.1 </strong>From the <strong>Navigation</strong> menu click on <strong>Administer > Site configuration > Spider Calendar</strong> and select the <strong>Calendar Themes</strong> tab. You can fill all the parameters or inherit the parameters of the theme from default themes. There are 11 default themes. You can use one of the default themes or create a new one. If you change the parameters of the default theme there is a big <strong>Reset Theme</strong> button for resetting default themes parameters to original.
      </p>
      <p>
        <strong>3.2 </strong>Click on the <strong>New</strong> link on the upper left hand of the window.
      </p>
      <p>
        <strong>3.3 Inherit from theme.</strong> You can choose to inherit the parameters from one of the default themes.
      </p>
      <div style='text-align:right;'><a target='_blank' href='http://web-dorado.com/4-creatingediting-calendar-themes/drupal-event-calendar-guide-step-4-1.html'>More</a></div>
      <h4><strong>Step 4: <a target='_blank' href='http://web-dorado.com/drupal-event-calendar-guide-step-5.html'>Publishing the Calendar.</a></strong></h4>
       <p>
        <strong>4.1 </strong>Click on <strong>Add content</strong> on the upper left hand of the screen and choose <strong>Spider Calendar</strong>.
      </p>
      <p>
        <strong>4.2 Title.</strong> Choose a header title for the calendar.
      </p>
      <p>
        <strong>4.3 Select Calendar.</strong> Select the calendar you want to publish.
      </p>
      <p>
        <strong>4.4 Select Theme.</strong> Choose a theme for the calendar.
      </p>
      <p>
        <strong>4.5 </strong>Click on the <strong>Save</strong> button.
      </p>
      <div style='text-align:right;'><a target='_blank' href='http://web-dorado.com/drupal-event-calendar-guide-step-5.html'>More</a></div>
      <h4><strong>Step 5: <a target='_blank' href='http://web-dorado.com/drupal-event-calendar-guide-step-6.html'>Publishing the Calendar in a Block.</a></strong></h4>
       <p>
        <strong>5.1 </strong>From the navigation menu select <strong>Administer > Site configuration > Spider Calendar</strong>.
      </p>
      <p>
        <strong>5.2 Number of Calendar Blocks.</strong> Specify the number of calendar blocks you want to publish and click <strong>Save Blocks Number.</strong>
      </p>
      <p>
        <strong>5.3 </strong>From the navigation menu select <strong>Administer > Site building</strong>.
      </p>
      <p>
        <strong>5.4 </strong>Locate the <strong>Spider Calendar</strong> blocks in the list and configure the blocks using <strong>the Configure</strong> link (Operations column).
      </p>
      <p>
        <strong>5.5 </strong>Click on the <strong>Save</strong> button.
      </p>
      <div style='text-align:right;'><a target='_blank' href='http://web-dorado.com/drupal-event-calendar-guide-step-6.html'>More</a></div>
      ", array(
        '!url_jscolor' => l(t('http://jscolor.com/release/jscolor-1.4.0.zip'), 'http://jscolor.com/release/jscolor-1.4.0.zip'),
        '!url_html_tiny' => l(t('http://github.com/downloads/tinymce/tinymce/tinymce_3.5.7.zip'), 'http://github.com/downloads/tinymce/tinymce/tinymce_3.5.7.zip'),
      )) . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_perm().
 */
function spider_calendar_perm() {
  return array('access Spider Calendar administration');
}

/**
 * Implements hook_menu().
 */
function spider_calendar_menu() {
  $items = array();
  $items['admin/settings/spider_calendar'] = array(
    'title' => 'Spider calendar',
    'description' => 'Spider calendar module allow to create calendars with own events.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_calendars'),
    'access arguments' => array('access Spider Calendar administration'),
    'file' => 'includes/spider_calendar_calendars.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/settings/spider_calendar/Calendars'] = array(
    'title' => 'Calendars',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_calendars'),
    'access arguments' => array('access Spider Calendar administration'),
    'weight' => 0,
    'file' => 'includes/spider_calendar_calendars.inc',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/settings/spider_calendar/Calendars/add'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_add_calendar'),
    'access arguments' => array('access Spider Calendar administration'),
    'weight' => 0,
    'file' => 'includes/spider_calendar_calendars.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/spider_calendar/Calendars/edit'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_edit_calendar'),
    'access arguments' => array('access Spider Calendar administration'),
    'weight' => 0,
    'file' => 'includes/spider_calendar_calendars.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/spider_calendar/Calendars/events'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_manage_events'),
    'access arguments' => array('access Spider Calendar administration'),
    'weight' => 0,
    'file' => 'includes/spider_calendar_manage_events.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/spider_calendar/Calendars/events/add'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_add_events'),
    'access arguments' => array('access Spider Calendar administration'),
    'weight' => 0,
    'file' => 'includes/spider_calendar_manage_events.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/spider_calendar/Calendar Themes'] = array(
    'title' => 'Calendar Themes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_cal_theme'),
    'access arguments' => array('access Spider Calendar administration'),
    'weight' => 1,
    'file' => 'includes/spider_calendar_cal_theme.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/settings/spider_calendar/Calendar Themes/add'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_add_theme'),
    'access arguments' => array('access Spider Calendar administration'),
    'weight' => 0,
    'file' => 'includes/spider_calendar_cal_theme.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/spider_calendar/Calendar Themes/add/preview_popup'] = array(
    'page callback' => 'spider_calendar_theme_preview',
    'access arguments' => array('access Spider Calendar administration'),
    'file' => 'includes/spider_calendar_cal_theme_preview.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/spider_calendar/Block Calendar Themes'] = array(
    'title' => 'Block Calendar Themes',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_block_cal_theme'),
    'access arguments' => array('access Spider Calendar administration'),
    'weight' => 2,
    'file' => 'includes/spider_calendar_block_cal_theme.inc',
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
  );
  $items['admin/settings/spider_calendar/Block Calendar Themes/add'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_add_block_theme'),
    'access arguments' => array('access Spider Calendar administration'),
    'weight' => 0,
    'file' => 'includes/spider_calendar_block_cal_theme.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/spider_calendar/Block Calendar Themes/add/preview_popup'] = array(
    'page callback' => 'spider_calendar_block_theme_preview',
    'access arguments' => array('access Spider Calendar administration'),
    'file' => 'includes/spider_calendar_block_cal_theme_preview.inc',
    'type' => MENU_CALLBACK,
  );
  $items['node/%spider_calendar_menu/see_more'] = array(
    'page callback' => 'spider_calendar_see_more',
    'access callback' => TRUE,
    'file' => 'includes/spider_calendar_see_more.inc',
  );
  $items['spider_calendar_block'] = array(
    'page callback' => 'spider_calendar_block_view',
    'page arguments' => array(3),
    'access callback' => TRUE,
    'file' => 'includes/spider_calendar_block_view.inc',
    'type' => MENU_CALLBACK,
  );
  $items['spider_calendar_block_events'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('spider_calendar_block_events_view'),
    'access callback' => TRUE,
    'file' => 'includes/spider_calendar_block_events_view.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_menu_load().
 */
function spider_calendar_menu_load($nid) {
  if (!is_numeric($nid)) {
    return FALSE;
  }
  $node = node_load($nid);
  if (!isset($node->type) || !in_array($node->type, spider_calendar_variable_get('spider_calendar_node_types'))) {
    return FALSE;
  }
  return $node;
}

/**
 * Function spider_calendar_variable_get().
 */
function spider_calendar_variable_get($variable) {
  switch ($variable) {
    case 'spider_calendar_allowed_tags':
      $result = variable_get('spider_calendar_allowed_tags', array(
        'a',
        'em',
        'strong',
        'code',
        'img'));
      break;

    case 'spider_calendar_node_types':
      $result = variable_get('spider_calendar_node_types', array('spider_calendar'));
      break;

    case 'spider_calendar_node_types_primary':
      $result = variable_get('spider_calendar_node_types_primary', array('spider_calendar'));
      break;
  }
  return $result;
}

/**
 * Implements hook_node_info().
 */
function spider_calendar_node_info() {
  return array(
    'spider_calendar' => array(
      'name' => t('Spider Calendar'),
      'module' => 'spider_calendar',
      'description' => t("Create a new calendar with Spider Calendar module"),
    ),
  );
}

/**
 * Implements hook_node_type().
 */
function spider_calendar_node_type($op, $info) {
  $spider_calendar_types = spider_calendar_variable_get('spider_calendar_node_types');
  $affected_type = isset($info->old_type) ? $info->old_type : $info->type;
  $key = array_search($affected_type, $spider_calendar_types);
  if ($key !== FALSE) {
    if ($op == 'update') {
      $spider_calendar_types[$key] = $info->type;
    }
    if ($op == 'delete') {
      unset($spider_calendar_types[$key]);
    }
    variable_set('spider_calendar_node_types', $spider_calendar_types);
  }
}

/**
 * Implements hook_access().
 */
function spider_calendar_access($op, $node) {
  global $user;
  if ($op == 'create') {
    return user_access('access Spider Calendar administration');
  }
  if ($op == 'update' || $op == 'delete') {
    if (user_access('access Spider Calendar administration') && ($user->uid == $node->uid)) {
      return TRUE;
    }
  }
}

/**
 * Implements hook_form().
 */
function spider_calendar_form(&$node, $form_state) {
  $type = node_get_types('type', $node);
  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => check_plain($type->title_label),
    '#required' => TRUE,
    '#default_value' => $node->title,
  );
  if (isset($node->nid)) {
    $result = db_query("SELECT * FROM {spider_calendar_form_table} WHERE vid = '%d'", $node->nid);
    $cal_row = db_fetch_array($result);
    $default_value = $cal_row['calendar'];
  }
  else {
    $default_value = 0;
  }
  $calendars = spider_calendar_get_calendars_array();
  $form['select_calendars'] = array(
    '#type' => 'select',
    '#title' => t('Select calendar'),
    '#description' => t('Create calendars on !url.', array(
      '!url' => l(t('admin/settings/spider_calendar/Calendars/add'), url('admin/settings/spider_calendar/Calendars/add',
        array('absolute' => TRUE))))),
    '#default_value' => $default_value,
    '#required' => FALSE,
    '#options' => $calendars,
  );
  $form['select_themes'] = array(
    '#prefix' => '<div class="messages warning">' . t('Themes are disabled for the non-commercial version.') . '</div><a href="http://web-dorado.com/files/fromSpiderCalendarDrupal.php" target="_blank" style="color:red; text-decoration:none; float:right;"><img src="' . base_path() . drupal_get_path('module', 'spider_calendar') . '/images/header.png" border="0" alt="www.web-dorado.com" width="215"><br /><div style="float:right;">' . t('Get the full version') . '&nbsp;&nbsp;&nbsp;&nbsp;</div></a>',
    '#type' => 'select',
    '#title' => t('Select theme'),
    '#description' => t('Select the calendar theme.'),
    '#required' => FALSE,
    '#disabled' => TRUE,
    '#options' => array('Blue'),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_insert().
 */
function spider_calendar_insert($node) {
  $type = 'spider_calendar';
  $title = $node->select_calendars;
  $theme = 12;
  db_query('INSERT INTO {spider_calendar_form_table}(vid, type, calendar, theme) VALUES("' . $node->nid . '","' . $type . '", "' . $title . '", "' . $theme . '")');
}

/**
 * Implements hook_update().
 */
function spider_calendar_update($node) {
  $title = $node->select_calendars;
  $theme = 12;
  db_query("UPDATE {spider_calendar_form_table} SET calendar='%d', theme='%d' WHERE vid='%d'", $title, $theme, $node->nid);
}

/**
 * Implements hook_delete().
 */
function spider_calendar_delete($node) {
  db_query('DELETE FROM {spider_calendar_form_table} WHERE vid = %d', $node->nid);
}

/**
 * Implements hook_view().
 */
function spider_calendar_view($node, $teaser = FALSE, $page = FALSE) {
  $node = node_prepare($node, $teaser);
  if ($page) {
    $select_calendars = db_result(db_query("SELECT calendar FROM {spider_calendar_form_table} WHERE  vid = '%d'", $node->nid));
    if ($select_calendars == -1 || $select_calendars == 0 || !db_result(db_query("SELECT id FROM {spider_calendar_calendar_table} WHERE published=1 and id='%d'", $select_calendars))) {
      $error_message = t('The calendar is not chosen. Select calendar !url.', array(
        '!url' => l(t('here'), url('node/' . $node->nid . '/edit',
          array('absolute' => TRUE)))));
      drupal_set_message($error_message, 'error', FALSE);
      $node_view = '';
    }
    else {
      require_once "includes/spider_calendar_view.inc";
      $cal_theme = db_result(db_query("SELECT theme FROM {spider_calendar_form_table} WHERE vid='%d'", $node->nid));
      $node_view = spider_calendar_content_view($select_calendars, $cal_theme, $node->nid);
    }
  }
  else {
    $node_view = '';
  }
  $node->content['spider_calendar'] = array(
    '#value' => $node_view,
  );
  return $node;
}

/**
 * Function spider_calendar_get_calendars_array().
 */
function spider_calendar_get_calendars_array() {
  $calendar = array();
  $calendar[0] = t('-Select calendar-');
  $result = db_query("SELECT id,title FROM {spider_calendar_calendar_table} WHERE published=1 ORDER BY title");
  while ($title = db_fetch_array($result)) {
    $calendar[$title['id']] = $title['title'];
  }
  return $calendar;
}

/**
 * Implements hook_block().
 */
function spider_calendar_block($op = 'list', $delta = 0, $edit = array()) {
  require_once "includes/spider_calendar_block_view.inc";
  $result = db_query("SELECT id,title FROM {spider_calendar_block_theme_table} ORDER BY title");
  while ($title = db_fetch_array($result)) {
    $themes_array[$title['id']] = $title['title'];
  }
  $spider_calendar_block_count = db_result(db_query("SELECT block_number FROM {spider_calendar_block_number_table} WHERE id='%d'", 1));
  $test = db_result(db_query("SELECT title FROM {spider_calendar_calendar_table}"));
  $calendars = spider_calendar_get_calendars_array();
  if ($op == "list") {
    $block = array();
    for ($i = 0; $i < $spider_calendar_block_count; $i++) {
      $block[$i]["info"] = 'Spider Calendar ' . ($i + 1);
      $block[$i]["content"] = '';
    }
    return $block;
  }
  elseif ($op == 'view') {
    for ($i = 0; $i < $spider_calendar_block_count; $i++) {
      $selected_calendars_id = variable_get(('spider_calendar_block_select_calendars' . $i), -1);
      $selected_theme_id = 12;
      if ($selected_calendars_id != -1 && $selected_calendars_id != 0 && db_result(db_query("SELECT id FROM {spider_calendar_calendar_table} WHERE published=1 and id='%d'", $selected_calendars_id))) {
        $result = db_query("SELECT * FROM {spider_calendar_calendar_table} WHERE id='%d'", $selected_calendars_id);
        $row = db_fetch_array($result);
        switch ((int) $delta) {
          case $i:
            $block_content = '';
            $block['subject'] = '';
            $block['content'] = spider_calendar_block_view($row['id'], $selected_theme_id, $i);
            break;
        }
      }
      else {
        switch ((int) $delta) {
          case $i:
            $block_content = '';
            $block['subject'] = '';
            $block['content'] = '';
            break;
        }
      }
    }
    return $block;
  }
  elseif ($op == 'configure') {
    for ($i = 0; $i < $spider_calendar_block_count; $i++) {
      if ((int) $delta == $i) {
        $form['spider_calendar_block_select_calendars' . $i] = array(
          '#type' => 'select',
          '#title' => t('Select calendar'),
          '#description' => t('Select calendar, which you want to see in this block.'),
          '#default_value' => variable_get(('spider_calendar_block_select_calendars' . $i), 0),
          '#required' => FALSE,
          '#options' => $calendars,
        );
        $form['spider_calendar_block_select_themes' . $i] = array(
          '#prefix' => '<div class="messages warning">' . t('Themes are disabled for the non-commercial version.') . '</div><a href="http://web-dorado.com/files/fromSpiderCalendarDrupal.php" target="_blank" style="color:red; text-decoration:none; float:right;"><img src="' . base_path() . drupal_get_path('module', 'spider_calendar') . '/images/header.png" border="0" alt="www.web-dorado.com" width="215"><br /><div style="float:right;">' . t('Get the full version') . '&nbsp;&nbsp;&nbsp;&nbsp;</div></a>',
          '#type' => 'select',
          '#title' => t('Select theme'),
          '#description' => t('Select the Block Calendar theme.'),
          '#required' => FALSE,
          '#disabled' => TRUE,
          '#options' => array('Blue'),
        );
      }
    }
    return $form;
  }
  elseif ($op == 'save') {
    for ($i = 0; $i < $spider_calendar_block_count; $i++) {
      if ((int) $delta == $i) {
        variable_set('spider_calendar_block_select_calendars' . $i, $edit['spider_calendar_block_select_calendars' . $i]);
      }
    }
    return;
  }
}
